using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CSharpSandbox
{
    internal class StatesData
    {
        List<state> states = new List<state>();
        
        public void Main()
        {
            states.Add(new state() { Id = 631, ParentId = 358, NameEn = "Ariana", NameAr = "اريانة", ParentNameAr = "Ariana", ParentNameEn = "اريانة" });
            states.Add(new state() { Id = 534, ParentId = 358, NameEn = "Attadhamon", NameAr = "التظامن", ParentNameAr = "Ariana", ParentNameEn = "اريانة" });
            states.Add(new state() { Id = 530, ParentId = 358, NameEn = "Kalaat El Andalous  ", NameAr = "قلعة الأندلس", ParentNameAr = "Ariana", ParentNameEn = "اريانة" });
            states.Add(new state() { Id = 533, ParentId = 358, NameEn = "Mnihla", NameAr = "المنيهلة", ParentNameAr = "Ariana", ParentNameEn = "اريانة" });
            states.Add(new state() { Id = 531, ParentId = 358, NameEn = "Raoued", NameAr = "رواد", ParentNameAr = "Ariana", ParentNameEn = "اريانة" });
            states.Add(new state() { Id = 535, ParentId = 358, NameEn = "Sidi Thabet", NameAr = "سيدي ثابت", ParentNameAr = "Ariana", ParentNameEn = "اريانة" });
            states.Add(new state() { Id = 532, ParentId = 358, NameEn = "Soukra", NameAr = "سكرة", ParentNameAr = "Ariana", ParentNameEn = "اريانة" });
            states.Add(new state() { Id = 579, ParentId = 362, NameEn = "El Ayoun", NameAr = "العيون", ParentNameAr = "Kasserine", ParentNameEn = "القصرين" });
            states.Add(new state() { Id = 577, ParentId = 362, NameEn = "Feriana", NameAr = "فريانة", ParentNameAr = "Kasserine", ParentNameEn = "القصرين" });
            states.Add(new state() { Id = 578, ParentId = 362, NameEn = "Foussana", NameAr = "فوسانة", ParentNameAr = "Kasserine", ParentNameEn = "القصرين" });
            states.Add(new state() { Id = 582, ParentId = 362, NameEn = "Hassi Ferid", NameAr = "حاسي الفريد", ParentNameAr = "Kasserine", ParentNameEn = "القصرين" });
            states.Add(new state() { Id = 574, ParentId = 362, NameEn = "Hidra", NameAr = "حيدرة", ParentNameAr = "Kasserine", ParentNameEn = "القصرين" });
            states.Add(new state() { Id = 581, ParentId = 362, NameEn = "Jedliane", NameAr = "جدليان", ParentNameAr = "Kasserine", ParentNameEn = "القصرين" });
            states.Add(new state() { Id = 635, ParentId = 362, NameEn = "Kasserine", NameAr = "القصرين", ParentNameAr = "Kasserine", ParentNameEn = "القصرين" });
            states.Add(new state() { Id = 580, ParentId = 362, NameEn = "Majel Bel Abbes", NameAr = "ماجل بلعباس", ParentNameAr = "Kasserine", ParentNameEn = "القصرين" });
            states.Add(new state() { Id = 576, ParentId = 362, NameEn = "Sbiba", NameAr = "سبيبة", ParentNameAr = "Kasserine", ParentNameEn = "القصرين" });
            states.Add(new state() { Id = 575, ParentId = 362, NameEn = "Sbitla", NameAr = "سبيطلة", ParentNameAr = "Kasserine", ParentNameEn = "القصرين" });
            states.Add(new state() { Id = 573, ParentId = 362, NameEn = "Tala", NameAr = "تالة", ParentNameAr = "Kasserine", ParentNameEn = "القصرين" });
            states.Add(new state() { Id = 528, ParentId = 357, NameEn = "Bou Hajla", NameAr = "بوحجلة", ParentNameAr = "Kairouan", ParentNameEn = "القيروان" });
            states.Add(new state() { Id = 522, ParentId = 357, NameEn = "Chebika", NameAr = "الشبيكة", ParentNameAr = "Kairouan", ParentNameEn = "القيروان" });
            states.Add(new state() { Id = 529, ParentId = 357, NameEn = "Chrarda", NameAr = "الشراردة", ParentNameAr = "Kairouan", ParentNameEn = "القيروان" });
            states.Add(new state() { Id = 524, ParentId = 357, NameEn = "El Alaa ", NameAr = "العلاء", ParentNameAr = "Kairouan", ParentNameEn = "القيروان" });
            states.Add(new state() { Id = 523, ParentId = 357, NameEn = "Haffouz", NameAr = "حفوز", ParentNameAr = "Kairouan", ParentNameEn = "القيروان" });
            states.Add(new state() { Id = 526, ParentId = 357, NameEn = "Hajeb El Ayoun", NameAr = "حاجب العيون", ParentNameAr = "Kairouan", ParentNameEn = "القيروان" });
            states.Add(new state() { Id = 630, ParentId = 357, NameEn = "Kairouan", NameAr = "القيروان", ParentNameAr = "Kairouan", ParentNameEn = "القيروان" });
            states.Add(new state() { Id = 527, ParentId = 357, NameEn = "Nasrallah", NameAr = "نصرالله", ParentNameAr = "Kairouan", ParentNameEn = "القيروان" });
            states.Add(new state() { Id = 525, ParentId = 357, NameEn = "Oueslatia", NameAr = "الوسلاتية", ParentNameAr = "Kairouan", ParentNameEn = "القيروان" });
            states.Add(new state() { Id = 521, ParentId = 357, NameEn = "Sebikha", NameAr = "السبيخة", ParentNameAr = "Kairouan", ParentNameEn = "القيروان" });
            states.Add(new state() { Id = 590, ParentId = 363, NameEn = "Dahmani", NameAr = "الدهماني", ParentNameAr = "Le kef", ParentNameEn = "الكاف" });
            states.Add(new state() { Id = 583, ParentId = 363, NameEn = "El Ksour", NameAr = "القصور", ParentNameAr = "Le kef", ParentNameEn = "الكاف" });
            states.Add(new state() { Id = 585, ParentId = 363, NameEn = "Jerissa", NameAr = "الجريسة", ParentNameAr = "Le kef", ParentNameEn = "الكاف" });
            states.Add(new state() { Id = 587, ParentId = 363, NameEn = "Kalâa El Khasba", NameAr = "القلعة الخصبة", ParentNameAr = "Le kef", ParentNameEn = "الكاف" });
            states.Add(new state() { Id = 588, ParentId = 363, NameEn = "Kalaat Sinane", NameAr = "قلعة السنان", ParentNameAr = "Le kef", ParentNameEn = "الكاف" });
            states.Add(new state() { Id = 636, ParentId = 363, NameEn = "Le Kef", NameAr = "الكاف", ParentNameAr = "Le kef", ParentNameEn = "الكاف" });
            states.Add(new state() { Id = 584, ParentId = 363, NameEn = "Le Sers", NameAr = "السرس", ParentNameAr = "Le kef", ParentNameEn = "الكاف" });
            states.Add(new state() { Id = 589, ParentId = 363, NameEn = "Nebeur", NameAr = "نبر", ParentNameAr = "Le kef", ParentNameEn = "الكاف" });
            states.Add(new state() { Id = 591, ParentId = 363, NameEn = "Sakiet Sidi Youssef", NameAr = "ساقية سيدي يوسف", ParentNameAr = "Le kef", ParentNameEn = "الكاف" });
            states.Add(new state() { Id = 586, ParentId = 363, NameEn = "Tejerouine", NameAr = "تاجروين", ParentNameAr = "Le kef", ParentNameEn = "الكاف" });
            states.Add(new state() { Id = 1523, ParentId = 363, NameEn = "Tourief", NameAr = "الطويرف", ParentNameAr = "Le kef", ParentNameEn = "الكاف" });
            states.Add(new state() { Id = 601, ParentId = 364, NameEn = "Bekalta", NameAr = "البقالطة", ParentNameAr = "Monastir", ParentNameEn = "المنستير" });
            states.Add(new state() { Id = 603, ParentId = 364, NameEn = "Benbla", NameAr = "بنبلة", ParentNameAr = "Monastir", ParentNameEn = "المنستير" });
            states.Add(new state() { Id = 597, ParentId = 364, NameEn = "Beni Hassan", NameAr = "بني حسان", ParentNameAr = "Monastir", ParentNameEn = "المنستير" });
            states.Add(new state() { Id = 595, ParentId = 364, NameEn = "Jammel", NameAr = "جمال", ParentNameAr = "Monastir", ParentNameEn = "المنستير" });
            states.Add(new state() { Id = 602, ParentId = 364, NameEn = "Ksar Helal", NameAr = "قصر هلال", ParentNameAr = "Monastir", ParentNameEn = "المنستير" });
            states.Add(new state() { Id = 599, ParentId = 364, NameEn = "Ksibet Medyouni", NameAr = "قصيبة المديوني", ParentNameAr = "Monastir", ParentNameEn = "المنستير" });
            states.Add(new state() { Id = 598, ParentId = 364, NameEn = "Moknine", NameAr = "المكنين", ParentNameAr = "Monastir", ParentNameEn = "المنستير" });
            states.Add(new state() { Id = 637, ParentId = 364, NameEn = "Monastir", NameAr = "المنستير", ParentNameAr = "Monastir", ParentNameEn = "المنستير" });
            states.Add(new state() { Id = 593, ParentId = 364, NameEn = "Ouerdanine", NameAr = "الوردانين", ParentNameAr = "Monastir", ParentNameEn = "المنستير" });
            states.Add(new state() { Id = 592, ParentId = 364, NameEn = "Sahline", NameAr = "الساحلين", ParentNameAr = "Monastir", ParentNameEn = "المنستير" });
            states.Add(new state() { Id = 600, ParentId = 364, NameEn = "Sayada Lamta Bouhjar", NameAr = "صيادة", ParentNameAr = "Monastir", ParentNameEn = "المنستير" });
            states.Add(new state() { Id = 594, ParentId = 364, NameEn = "Teboulba", NameAr = "طبلبة", ParentNameAr = "Monastir", ParentNameEn = "المنستير" });
            states.Add(new state() { Id = 596, ParentId = 364, NameEn = "Zeramdine", NameAr = "زرامدين", ParentNameAr = "Monastir", ParentNameEn = "المنستير" });
            states.Add(new state() { Id = 427, ParentId = 345, NameEn = "Boumerdes", NameAr = "بومرداس", ParentNameAr = "Mahdia", ParentNameEn = "المهدية" });
            states.Add(new state() { Id = 424, ParentId = 345, NameEn = "Chebba", NameAr = "الشابة", ParentNameAr = "Mahdia", ParentNameEn = "المهدية" });
            states.Add(new state() { Id = 429, ParentId = 345, NameEn = "Chorbane", NameAr = "شربان", ParentNameAr = "Mahdia", ParentNameEn = "المهدية" });
            states.Add(new state() { Id = 619, ParentId = 345, NameEn = "El Jem", NameAr = "الجم", ParentNameAr = "Mahdia", ParentNameEn = "المهدية" });
            states.Add(new state() { Id = 430, ParentId = 345, NameEn = "Hbira", NameAr = "هبيرة", ParentNameAr = "Mahdia", ParentNameEn = "المهدية" });
            states.Add(new state() { Id = 423, ParentId = 345, NameEn = "Ksour Essef", NameAr = "قصور الساف", ParentNameAr = "Mahdia", ParentNameEn = "المهدية" });
            states.Add(new state() { Id = 618, ParentId = 345, NameEn = "Mahdia", NameAr = "المهدية", ParentNameAr = "Mahdia", ParentNameEn = "المهدية" });
            states.Add(new state() { Id = 425, ParentId = 345, NameEn = "Malloulech", NameAr = "مللولش", ParentNameAr = "Mahdia", ParentNameEn = "المهدية" });
            states.Add(new state() { Id = 431, ParentId = 345, NameEn = "Ouled Chamekh", NameAr = "أولاد شامخ", ParentNameAr = "Mahdia", ParentNameEn = "المهدية" });
            states.Add(new state() { Id = 1084, ParentId = 345, NameEn = "Rejiche", NameAr = "الرجيش", ParentNameAr = "Mahdia", ParentNameEn = "المهدية" });
            states.Add(new state() { Id = 426, ParentId = 345, NameEn = "Sidi Alouane", NameAr = "سيدي علوان", ParentNameAr = "Mahdia", ParentNameEn = "المهدية" });
            states.Add(new state() { Id = 428, ParentId = 345, NameEn = "Souassi", NameAr = "السواسي", ParentNameAr = "Mahdia", ParentNameEn = "المهدية" });
            states.Add(new state() { Id = 515, ParentId = 356, NameEn = "Amdoun", NameAr = "عمدون", ParentNameAr = "Beja", ParentNameEn = "باجة" });
            states.Add(new state() { Id = 629, ParentId = 356, NameEn = "Beja", NameAr = "باجة", ParentNameAr = "Beja", ParentNameEn = "باجة" });
            states.Add(new state() { Id = 519, ParentId = 356, NameEn = "Goubellat", NameAr = "قبلاط", ParentNameAr = "Beja", ParentNameEn = "باجة" });
            states.Add(new state() { Id = 520, ParentId = 356, NameEn = "Mejez El Bab", NameAr = "مجاز الباب", ParentNameAr = "Beja", ParentNameEn = "باجة" });
            states.Add(new state() { Id = 514, ParentId = 356, NameEn = "Nefza", NameAr = "نفزة", ParentNameAr = "Beja", ParentNameEn = "باجة" });
            states.Add(new state() { Id = 518, ParentId = 356, NameEn = "Teboursouk", NameAr = "تبرسق", ParentNameAr = "Beja", ParentNameEn = "باجة" });
            states.Add(new state() { Id = 517, ParentId = 356, NameEn = "Testour", NameAr = "تستور", ParentNameAr = "Beja", ParentNameEn = "باجة" });
            states.Add(new state() { Id = 516, ParentId = 356, NameEn = "Tibar", NameAr = "تيبار", ParentNameAr = "Beja", ParentNameEn = "باجة" });
            states.Add(new state() { Id = 622, ParentId = 349, NameEn = "Ben Arous", NameAr = "بن عروس", ParentNameAr = "Ben Arous", ParentNameEn = "بن عروس" });
            states.Add(new state() { Id = 453, ParentId = 349, NameEn = "Boumhel Bassatine", NameAr = "بومهل البساتين", ParentNameAr = "Ben Arous", ParentNameEn = "بن عروس" });
            states.Add(new state() { Id = 447, ParentId = 349, NameEn = "El Mourouj", NameAr = "المروج", ParentNameAr = "Ben Arous", ParentNameEn = "بن عروس" });
            states.Add(new state() { Id = 450, ParentId = 349, NameEn = "Ezzahra", NameAr = "الزهرة", ParentNameAr = "Ben Arous", ParentNameEn = "بن عروس" });
            states.Add(new state() { Id = 446, ParentId = 349, NameEn = "Fouchana", NameAr = "فوشانة", ParentNameAr = "Ben Arous", ParentNameEn = "بن عروس" });
            states.Add(new state() { Id = 452, ParentId = 349, NameEn = "Hammam Chatt", NameAr = "حمام الشط", ParentNameAr = "Ben Arous", ParentNameEn = "بن عروس" });
            states.Add(new state() { Id = 451, ParentId = 349, NameEn = "Hammam Lif", NameAr = "حمام الأنف", ParentNameAr = "Ben Arous", ParentNameEn = "بن عروس" });
            states.Add(new state() { Id = 454, ParentId = 349, NameEn = "Medina Jedida", NameAr = "المدينة الجديدة", ParentNameAr = "Ben Arous", ParentNameEn = "بن عروس" });
            states.Add(new state() { Id = 448, ParentId = 349, NameEn = "Megrine", NameAr = "مقرين", ParentNameAr = "Ben Arous", ParentNameEn = "بن عروس" });
            states.Add(new state() { Id = 445, ParentId = 349, NameEn = "Mohamedia", NameAr = "المحمدية", ParentNameAr = "Ben Arous", ParentNameEn = "بن عروس" });
            states.Add(new state() { Id = 444, ParentId = 349, NameEn = "Mornag", NameAr = "مرناق", ParentNameAr = "Ben Arous", ParentNameEn = "بن عروس" });
            states.Add(new state() { Id = 449, ParentId = 349, NameEn = "Rades", NameAr = "رادس", ParentNameAr = "Ben Arous", ParentNameEn = "بن عروس" });
            states.Add(new state() { Id = 572, ParentId = 361, NameEn = "Al Khitmin", NameAr = "الختمين", ParentNameAr = "Bizerte", ParentNameEn = "بنزرت" });
            states.Add(new state() { Id = 569, ParentId = 361, NameEn = "Al Matlin ", NameAr = "المتلين", ParentNameAr = "Bizerte", ParentNameEn = "بنزرت" });
            states.Add(new state() { Id = 571, ParentId = 361, NameEn = "Aousja", NameAr = "عوسجة", ParentNameAr = "Bizerte", ParentNameEn = "بنزرت" });
            states.Add(new state() { Id = 634, ParentId = 361, NameEn = "Bizerte", NameAr = "بنزرت", ParentNameAr = "Bizerte", ParentNameEn = "بنزرت" });
            states.Add(new state() { Id = 566, ParentId = 361, NameEn = "El Alia", NameAr = "العالية", ParentNameAr = "Bizerte", ParentNameEn = "بنزرت" });
            states.Add(new state() { Id = 563, ParentId = 361, NameEn = "Ghar El Melh", NameAr = "غار الملح", ParentNameAr = "Bizerte", ParentNameEn = "بنزرت" });
            states.Add(new state() { Id = 560, ParentId = 361, NameEn = "Ghezala", NameAr = "غزالة", ParentNameAr = "Bizerte", ParentNameEn = "بنزرت" });
            states.Add(new state() { Id = 558, ParentId = 361, NameEn = "Joumine", NameAr = "جومين", ParentNameAr = "Bizerte", ParentNameEn = "بنزرت" });
            states.Add(new state() { Id = 559, ParentId = 361, NameEn = "Mateur", NameAr = "ماطر", ParentNameAr = "Bizerte", ParentNameEn = "بنزرت" });
            states.Add(new state() { Id = 562, ParentId = 361, NameEn = "Menzel Bourguiba", NameAr = "منزل برقيبة", ParentNameAr = "Bizerte", ParentNameEn = "بنزرت" });
            states.Add(new state() { Id = 561, ParentId = 361, NameEn = "Menzel Jemil", NameAr = "منزل جميل", ParentNameAr = "Bizerte", ParentNameEn = "بنزرت" });
            states.Add(new state() { Id = 564, ParentId = 361, NameEn = "Ras Jebel", NameAr = "رأس الجبل", ParentNameAr = "Bizerte", ParentNameEn = "بنزرت" });
            states.Add(new state() { Id = 557, ParentId = 361, NameEn = "Sejnane", NameAr = "سجنان", ParentNameAr = "Bizerte", ParentNameEn = "بنزرت" });
            states.Add(new state() { Id = 565, ParentId = 361, NameEn = "Tinja", NameAr = "تينجة", ParentNameAr = "Bizerte", ParentNameEn = "بنزرت" });
            states.Add(new state() { Id = 567, ParentId = 361, NameEn = "Utique", NameAr = "أوتيك", ParentNameAr = "Bizerte", ParentNameEn = "بنزرت" });
            states.Add(new state() { Id = 568, ParentId = 361, NameEn = "Zarzouna", NameAr = "جرزونة", ParentNameAr = "Bizerte", ParentNameEn = "بنزرت" });
            states.Add(new state() { Id = 570, ParentId = 361, NameEn = "Zouaouine", NameAr = "الزواوين", ParentNameAr = "Bizerte", ParentNameEn = "بنزرت" });
            states.Add(new state() { Id = 474, ParentId = 351, NameEn = "Bir Lahmar", NameAr = "بئر الأحمر", ParentNameAr = "Tataouine", ParentNameEn = "تطاوين" });
            states.Add(new state() { Id = 1524, ParentId = 351, NameEn = "Bni Mhira", NameAr = "بني مهيرة", ParentNameAr = "Tataouine", ParentNameEn = "تطاوين" });
            states.Add(new state() { Id = 475, ParentId = 351, NameEn = "Borj El Khadra", NameAr = "برج الخضراء", ParentNameAr = "Tataouine", ParentNameEn = "تطاوين" });
            states.Add(new state() { Id = 470, ParentId = 351, NameEn = "Dehiba", NameAr = "الذهيبة", ParentNameAr = "Tataouine", ParentNameEn = "تطاوين" });
            states.Add(new state() { Id = 476, ParentId = 351, NameEn = "El Borma", NameAr = "البرمة", ParentNameAr = "Tataouine", ParentNameEn = "تطاوين" });
            states.Add(new state() { Id = 473, ParentId = 351, NameEn = "Ghomrassen", NameAr = "غمراسن", ParentNameAr = "Tataouine", ParentNameEn = "تطاوين" });
            states.Add(new state() { Id = 471, ParentId = 351, NameEn = "Remada", NameAr = "رمادة", ParentNameAr = "Tataouine", ParentNameEn = "تطاوين" });
            states.Add(new state() { Id = 472, ParentId = 351, NameEn = "Smar", NameAr = "السمار", ParentNameAr = "Tataouine", ParentNameEn = "تطاوين" });
            states.Add(new state() { Id = 624, ParentId = 351, NameEn = "Tataouine", NameAr = "تطاوين", ParentNameAr = "Tataouine", ParentNameEn = "تطاوين" });
            states.Add(new state() { Id = 478, ParentId = 352, NameEn = "Degueche", NameAr = "دقاش", ParentNameAr = "Tozeur", ParentNameEn = "توزر" });
            states.Add(new state() { Id = 481, ParentId = 352, NameEn = "Hammat Al Jarid", NameAr = "حامة الجريد", ParentNameAr = "Tozeur", ParentNameEn = "توزر" });
            states.Add(new state() { Id = 479, ParentId = 352, NameEn = "Hazoua", NameAr = "حزوة", ParentNameAr = "Tozeur", ParentNameEn = "توزر" });
            states.Add(new state() { Id = 477, ParentId = 352, NameEn = "Nefta", NameAr = "نفطة", ParentNameAr = "Tozeur", ParentNameEn = "توزر" });
            states.Add(new state() { Id = 480, ParentId = 352, NameEn = "Tameghza", NameAr = "تمغزة", ParentNameAr = "Tozeur", ParentNameEn = "توزر" });
            states.Add(new state() { Id = 625, ParentId = 352, NameEn = "Tozeur", NameAr = "توزر", ParentNameAr = "Tozeur", ParentNameEn = "توزر" });
            states.Add(new state() { Id = 404, ParentId = 342, NameEn = "Bab Bhar", NameAr = "باب بحر", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 395, ParentId = 342, NameEn = "Bab Souika", NameAr = "باب سويقة", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 394, ParentId = 342, NameEn = "Bardo", NameAr = "باردو", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 387, ParentId = 342, NameEn = "Carthage", NameAr = "قرطاج", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 389, ParentId = 342, NameEn = "Cite El Khadhra", NameAr = "حي الخضراء", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 397, ParentId = 342, NameEn = "El Hrairia", NameAr = "الحرايرية", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 400, ParentId = 342, NameEn = "El Kabaria", NameAr = "كبارية", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 390, ParentId = 342, NameEn = "El Menzah", NameAr = "المنزه", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 399, ParentId = 342, NameEn = "El Ouardia", NameAr = "الوردية", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 393, ParentId = 342, NameEn = "Ettahrir", NameAr = "التحرير", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 396, ParentId = 342, NameEn = "Ezzouhour", NameAr = "الزهور", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 401, ParentId = 342, NameEn = "Jebel Jelloud", NameAr = "جبل جلود", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 388, ParentId = 342, NameEn = "Goulette", NameAr = "حلق الواد", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 386, ParentId = 342, NameEn = "La Marsa", NameAr = "المرسى", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 403, ParentId = 342, NameEn = "La Medina", NameAr = "المدينة", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 406, ParentId = 342, NameEn = "Le Kram", NameAr = "الكرم", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 391, ParentId = 342, NameEn = "Omrane", NameAr = "العمران", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 392, ParentId = 342, NameEn = "Omrane Superieur", NameAr = "العمران الأعلى", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 402, ParentId = 342, NameEn = "Sidi El Bechir", NameAr = "سيدي البشير", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 398, ParentId = 342, NameEn = "Sidi Hassine", NameAr = "سيدي حسين", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 405, ParentId = 342, NameEn = "Sijoumi", NameAr = "السيجومي", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 615, ParentId = 342, NameEn = "Tunis", NameAr = "مدينة تونس", ParentNameAr = "Tunis", ParentNameEn = "تونس" });
            states.Add(new state() { Id = 498, ParentId = 354, NameEn = "Ain Drahem", NameAr = "عين دراهم", ParentNameAr = "Jendouba", ParentNameEn = "جندوبة" });
            states.Add(new state() { Id = 503, ParentId = 354, NameEn = "Balta Bou Aouane", NameAr = "بلطة بوعوان", ParentNameAr = "Jendouba", ParentNameEn = "جندوبة" });
            states.Add(new state() { Id = 499, ParentId = 354, NameEn = "Bou Salem", NameAr = "بوسالم", ParentNameAr = "Jendouba", ParentNameEn = "جندوبة" });
            states.Add(new state() { Id = 502, ParentId = 354, NameEn = "Fernana", NameAr = "فرنانة", ParentNameAr = "Jendouba", ParentNameEn = "جندوبة" });
            states.Add(new state() { Id = 501, ParentId = 354, NameEn = "Ghardimaou", NameAr = "غار الدماء", ParentNameAr = "Jendouba", ParentNameEn = "جندوبة" });
            states.Add(new state() { Id = 627, ParentId = 354, NameEn = "Jendouba", NameAr = "جندوبة", ParentNameAr = "Jendouba", ParentNameEn = "جندوبة" });
            states.Add(new state() { Id = 500, ParentId = 354, NameEn = "Oued Mliz", NameAr = "واد مليز", ParentNameAr = "Jendouba", ParentNameEn = "جندوبة" });
            states.Add(new state() { Id = 497, ParentId = 354, NameEn = "Tabarka", NameAr = "طبرقة", ParentNameAr = "Jendouba", ParentNameEn = "جندوبة" });
            states.Add(new state() { Id = 410, ParentId = 343, NameEn = "Bir Mcherga", NameAr = "بئر مشارقة", ParentNameAr = "Zaghouan", ParentNameEn = "زغوان" });
            states.Add(new state() { Id = 411, ParentId = 343, NameEn = "El Fahs", NameAr = "الفحص", ParentNameAr = "Zaghouan", ParentNameEn = "زغوان" });
            states.Add(new state() { Id = 412, ParentId = 343, NameEn = "Nadhour", NameAr = "الناظور", ParentNameAr = "Zaghouan", ParentNameEn = "زغوان" });
            states.Add(new state() { Id = 413, ParentId = 343, NameEn = "Saouaf", NameAr = "صواف", ParentNameAr = "Zaghouan", ParentNameEn = "زغوان" });
            states.Add(new state() { Id = 616, ParentId = 343, NameEn = "Zaghouan", NameAr = "زغوان", ParentNameAr = "Zaghouan", ParentNameEn = "زغوان" });
            states.Add(new state() { Id = 409, ParentId = 343, NameEn = "Zeriba", NameAr = "الزريبة", ParentNameAr = "Zaghouan", ParentNameEn = "زغوان" });
            states.Add(new state() { Id = 417, ParentId = 344, NameEn = "Bargou", NameAr = "برقو", ParentNameAr = "Siliana", ParentNameEn = "سليانة" });
            states.Add(new state() { Id = 420, ParentId = 344, NameEn = "Bouarada", NameAr = "بوعرادة", ParentNameAr = "Siliana", ParentNameEn = "سليانة" });
            states.Add(new state() { Id = 419, ParentId = 344, NameEn = "El Aroussa", NameAr = "العروسة", ParentNameAr = "Siliana", ParentNameEn = "سليانة" });
            states.Add(new state() { Id = 418, ParentId = 344, NameEn = "Gaafour", NameAr = "قعفور", ParentNameAr = "Siliana", ParentNameEn = "سليانة" });
            states.Add(new state() { Id = 414, ParentId = 344, NameEn = "Kesra", NameAr = "كسرى", ParentNameAr = "Siliana", ParentNameEn = "سليانة" });
            states.Add(new state() { Id = 421, ParentId = 344, NameEn = "Le Krib", NameAr = "الكريب", ParentNameAr = "Siliana", ParentNameEn = "سليانة" });
            states.Add(new state() { Id = 415, ParentId = 344, NameEn = "Makther", NameAr = "مكثر", ParentNameAr = "Siliana", ParentNameEn = "سليانة" });
            states.Add(new state() { Id = 416, ParentId = 344, NameEn = "Rouhia", NameAr = "الروحية", ParentNameAr = "Siliana", ParentNameEn = "سليانة" });
            states.Add(new state() { Id = 422, ParentId = 344, NameEn = "Sidi Bou Rouis", NameAr = "بورويس", ParentNameAr = "Siliana", ParentNameEn = "سليانة" });
            states.Add(new state() { Id = 617, ParentId = 344, NameEn = "Siliana", NameAr = "سليانة", ParentNameAr = "Siliana", ParentNameEn = "سليانة" });
            states.Add(new state() { Id = 437, ParentId = 348, NameEn = "Akouda", NameAr = "أكودة", ParentNameAr = "Sousse", ParentNameEn = "سوسة" });
            states.Add(new state() { Id = 433, ParentId = 348, NameEn = "Bouficha", NameAr = "بوفيشة", ParentNameAr = "Sousse", ParentNameEn = "سوسة" });
            states.Add(new state() { Id = 434, ParentId = 348, NameEn = "Enfida", NameAr = "النفيضة", ParentNameAr = "Sousse", ParentNameEn = "سوسة" });
            states.Add(new state() { Id = 438, ParentId = 348, NameEn = "Hammam Sousse", NameAr = "حمام سوسة", ParentNameAr = "Sousse", ParentNameEn = "سوسة" });
            states.Add(new state() { Id = 435, ParentId = 348, NameEn = "Hergla", NameAr = "هرقلة", ParentNameAr = "Sousse", ParentNameEn = "سوسة" });
            states.Add(new state() { Id = 439, ParentId = 348, NameEn = "Kalaa Kebira", NameAr = "القلعة الكبيرة", ParentNameAr = "Sousse", ParentNameEn = "سوسة" });
            states.Add(new state() { Id = 443, ParentId = 348, NameEn = "Kalaa Seghira", NameAr = "القلعة الصغيرة", ParentNameAr = "Sousse", ParentNameEn = "سوسة" });
            states.Add(new state() { Id = 442, ParentId = 348, NameEn = "Koundar", NameAr = "كندار", ParentNameAr = "Sousse", ParentNameEn = "سوسة" });
            states.Add(new state() { Id = 440, ParentId = 348, NameEn = "Msaken", NameAr = "مساكن", ParentNameAr = "Sousse", ParentNameEn = "سوسة" });
            states.Add(new state() { Id = 436, ParentId = 348, NameEn = "Sidi Bouali", NameAr = "سيدي بوعلي", ParentNameAr = "Sousse", ParentNameEn = "سوسة" });
            states.Add(new state() { Id = 441, ParentId = 348, NameEn = "Sidi Elheni", NameAr = "سيدي الهاني", ParentNameAr = "Sousse", ParentNameEn = "سوسة" });
            states.Add(new state() { Id = 621, ParentId = 348, NameEn = "Sousse", NameAr = "سوسة", ParentNameAr = "Sousse", ParentNameEn = "سوسة" });
            states.Add(new state() { Id = 508, ParentId = 355, NameEn = "Bir El Hafey", NameAr = "بئر الحفي", ParentNameAr = "Sidi Bouzid", ParentNameEn = "سيدي بوزيد" });
            states.Add(new state() { Id = 1522, ParentId = 355, NameEn = "Hichria", NameAr = "الهيشرية", ParentNameAr = "Sidi Bouzid", ParentNameEn = "سيدي بوزيد" });
            states.Add(new state() { Id = 506, ParentId = 355, NameEn = "Jelma", NameAr = "جلمة", ParentNameAr = "Sidi Bouzid", ParentNameEn = "سيدي بوزيد" });
            states.Add(new state() { Id = 505, ParentId = 355, NameEn = "Meknassi", NameAr = "المكناسي", ParentNameAr = "Sidi Bouzid", ParentNameEn = "سيدي بوزيد" });
            states.Add(new state() { Id = 510, ParentId = 355, NameEn = "Menzel Bouzayane", NameAr = "منزل بو زيان", ParentNameAr = "Sidi Bouzid", ParentNameEn = "سيدي بوزيد" });
            states.Add(new state() { Id = 511, ParentId = 355, NameEn = "Mezouna", NameAr = "المزونة", ParentNameAr = "Sidi Bouzid", ParentNameEn = "سيدي بوزيد" });
            states.Add(new state() { Id = 512, ParentId = 355, NameEn = "Ouled Haffouz", NameAr = "أولاد حفوز", ParentNameAr = "Sidi Bouzid", ParentNameEn = "سيدي بوزيد" });
            states.Add(new state() { Id = 504, ParentId = 355, NameEn = "Regueb", NameAr = "الرقاب", ParentNameAr = "Sidi Bouzid", ParentNameEn = "سيدي بوزيد" });
            states.Add(new state() { Id = 507, ParentId = 355, NameEn = "Sabbalet Ouled Asker", NameAr = "سبالة أولاد عسكر", ParentNameAr = "Sidi Bouzid", ParentNameEn = "سيدي بوزيد" });
            states.Add(new state() { Id = 509, ParentId = 355, NameEn = "Sidi Ali Ben Aoun", NameAr = "سيدي علي بن عون", ParentNameAr = "Sidi Bouzid", ParentNameEn = "سيدي بوزيد" });
            states.Add(new state() { Id = 628, ParentId = 355, NameEn = "Sidi Bouzid", NameAr = "سيدي بوزيد", ParentNameAr = "Sidi Bouzid", ParentNameEn = "سيدي بوزيد" });
            states.Add(new state() { Id = 513, ParentId = 355, NameEn = "Souk Jedid", NameAr = "سوق الجديد", ParentNameAr = "Sidi Bouzid", ParentNameEn = "سيدي بوزيد" });
            states.Add(new state() { Id = 540, ParentId = 359, NameEn = "Agareb", NameAr = "عقارب", ParentNameAr = "Sfax", ParentNameEn = "صفاقس" });
            states.Add(new state() { Id = 538, ParentId = 359, NameEn = "Bir Ali Ben Khelifa", NameAr = "بئر علي بن خليفة", ParentNameAr = "Sfax", ParentNameEn = "صفاقس" });
            states.Add(new state() { Id = 545, ParentId = 359, NameEn = "El Amra", NameAr = "العامرة", ParentNameAr = "Sfax", ParentNameEn = "صفاقس" });
            states.Add(new state() { Id = 541, ParentId = 359, NameEn = "El Hencha", NameAr = "الحنشة", ParentNameAr = "Sfax", ParentNameEn = "صفاقس" });
            states.Add(new state() { Id = 539, ParentId = 359, NameEn = "Ghraiba", NameAr = "الغريبة", ParentNameAr = "Sfax", ParentNameEn = "صفاقس" });
            states.Add(new state() { Id = 536, ParentId = 359, NameEn = "Jebiniana", NameAr = "جبنيانة", ParentNameAr = "Sfax", ParentNameEn = "صفاقس" });
            states.Add(new state() { Id = 543, ParentId = 359, NameEn = "Kerkennah El Attaya", NameAr = "قرقنة العطايا", ParentNameAr = "Sfax", ParentNameEn = "صفاقس" });
            states.Add(new state() { Id = 544, ParentId = 359, NameEn = "Kerkennah Mellita", NameAr = "قرقنة مليتة", ParentNameAr = "Sfax", ParentNameEn = "صفاقس" });
            states.Add(new state() { Id = 537, ParentId = 359, NameEn = "Mahres", NameAr = "المحرس", ParentNameAr = "Sfax", ParentNameEn = "صفاقس" });
            states.Add(new state() { Id = 542, ParentId = 359, NameEn = "Menzel Chaker", NameAr = "منزل شاكر", ParentNameAr = "Sfax", ParentNameEn = "صفاقس" });
            states.Add(new state() { Id = 548, ParentId = 359, NameEn = "Sakiet Eddaier", NameAr = "ساقية الداير", ParentNameAr = "Sfax", ParentNameEn = "صفاقس" });
            states.Add(new state() { Id = 547, ParentId = 359, NameEn = "Sakiet Ezzit", NameAr = "ساقية الزيت", ParentNameAr = "Sfax", ParentNameEn = "صفاقس" });
            states.Add(new state() { Id = 632, ParentId = 359, NameEn = "Sfax", NameAr = "صفاقس", ParentNameAr = "Sfax", ParentNameEn = "صفاقس" });
            states.Add(new state() { Id = 546, ParentId = 359, NameEn = "Skhira", NameAr = "الصخيرة", ParentNameAr = "Sfax", ParentNameEn = "صفاقس" });
            states.Add(new state() { Id = 549, ParentId = 359, NameEn = "Tina", NameAr = "تينة", ParentNameAr = "Sfax", ParentNameEn = "صفاقس" });
            states.Add(new state() { Id = 1024, ParentId = 347, NameEn = "El Hamma", NameAr = "الحامة", ParentNameAr = "Gabes", ParentNameEn = "قابس" });
            states.Add(new state() { Id = 620, ParentId = 347, NameEn = "Gabes", NameAr = "قابس", ParentNameAr = "Gabes", ParentNameEn = "قابس" });
            states.Add(new state() { Id = 1019, ParentId = 347, NameEn = "Ghannouch", NameAr = "غنوش", ParentNameAr = "Gabes", ParentNameEn = "قابس" });
            states.Add(new state() { Id = 1020, ParentId = 347, NameEn = "Mareth", NameAr = "مارث", ParentNameAr = "Gabes", ParentNameEn = "قابس" });
            states.Add(new state() { Id = 1022, ParentId = 347, NameEn = "Matmata", NameAr = "مطماطا", ParentNameAr = "Gabes", ParentNameEn = "قابس" });
            states.Add(new state() { Id = 1023, ParentId = 347, NameEn = "Matmata Nouvelle", NameAr = "مطماطا الجديدة", ParentNameAr = "Gabes", ParentNameEn = "قابس" });
            states.Add(new state() { Id = 1021, ParentId = 347, NameEn = "Menzel Habib", NameAr = "منزل حبيب", ParentNameAr = "Gabes", ParentNameEn = "قابس" });
            states.Add(new state() { Id = 1025, ParentId = 347, NameEn = "Metouia", NameAr = "المطوية", ParentNameAr = "Gabes", ParentNameEn = "قابس" });
            states.Add(new state() { Id = 484, ParentId = 1012, NameEn = "Douz", NameAr = "دوز", ParentNameAr = "Kebili", ParentNameEn = "قبلي" });
            states.Add(new state() { Id = 485, ParentId = 1012, NameEn = "El Faouar", NameAr = "الفوار", ParentNameAr = "Kebili", ParentNameEn = "قبلي" });
            states.Add(new state() { Id = 482, ParentId = 1012, NameEn = "Kebili", NameAr = "قبلي", ParentNameAr = "Kebili", ParentNameEn = "قبلي" });
            states.Add(new state() { Id = 486, ParentId = 1012, NameEn = "Matrouha", NameAr = "المطروحة", ParentNameAr = "Kebili", ParentNameEn = "قبلي" });
            states.Add(new state() { Id = 487, ParentId = 1012, NameEn = "Rjim Maatoug", NameAr = "رجيم معتوق", ParentNameAr = "Kebili", ParentNameEn = "قبلي" });
            states.Add(new state() { Id = 483, ParentId = 1012, NameEn = "Souk El Ahad", NameAr = "سوق الأحد", ParentNameAr = "Kebili", ParentNameEn = "قبلي" });
            states.Add(new state() { Id = 612, ParentId = 365, NameEn = "Belkhir", NameAr = "بلخير", ParentNameAr = "Gafsa", ParentNameEn = "قفصة" });
            states.Add(new state() { Id = 611, ParentId = 365, NameEn = "El Guettar", NameAr = "القطار", ParentNameAr = "Gafsa", ParentNameEn = "قفصة" });
            states.Add(new state() { Id = 608, ParentId = 365, NameEn = "El Ksar", NameAr = "القصر", ParentNameAr = "Gafsa", ParentNameEn = "قفصة" });
            states.Add(new state() { Id = 638, ParentId = 365, NameEn = "Gafsa", NameAr = "قفصة", ParentNameAr = "Gafsa", ParentNameEn = "قفصة" });
            states.Add(new state() { Id = 607, ParentId = 365, NameEn = "Mdhilla", NameAr = "المظيلة", ParentNameAr = "Gafsa", ParentNameEn = "قفصة" });
            states.Add(new state() { Id = 606, ParentId = 365, NameEn = "Metlaoui", NameAr = "المتلوي", ParentNameAr = "Gafsa", ParentNameEn = "قفصة" });
            states.Add(new state() { Id = 604, ParentId = 365, NameEn = "Moulares", NameAr = "أم العرايس", ParentNameAr = "Gafsa", ParentNameEn = "قفصة" });
            states.Add(new state() { Id = 605, ParentId = 365, NameEn = "Redyef", NameAr = "الرديف", ParentNameAr = "Gafsa", ParentNameEn = "قفصة" });
            states.Add(new state() { Id = 609, ParentId = 365, NameEn = "Sened", NameAr = "السند", ParentNameAr = "Gafsa", ParentNameEn = "قفصة" });
            states.Add(new state() { Id = 610, ParentId = 365, NameEn = "Sidi Aich", NameAr = "سيدي عيش", ParentNameAr = "Gafsa", ParentNameEn = "قفصة" });
            states.Add(new state() { Id = 488, ParentId = 353, NameEn = "Ben Guerdene", NameAr = "بن قردان", ParentNameAr = "Medenine", ParentNameEn = "مدنين" });
            states.Add(new state() { Id = 489, ParentId = 353, NameEn = "Beni Khedach", NameAr = "بني خداش", ParentNameAr = "Medenine", ParentNameEn = "مدنين" });
            states.Add(new state() { Id = 493, ParentId = 353, NameEn = "Djerba Ajim", NameAr = "جربة آجيم", ParentNameAr = "Medenine", ParentNameEn = "مدنين" });
            states.Add(new state() { Id = 491, ParentId = 353, NameEn = "Djerba El May", NameAr = "جربة الماي", ParentNameAr = "Medenine", ParentNameEn = "مدنين" });
            states.Add(new state() { Id = 494, ParentId = 353, NameEn = "Djerba Houmt Souk", NameAr = "جربة حومة السوق", ParentNameAr = "Medenine", ParentNameEn = "مدنين" });
            states.Add(new state() { Id = 492, ParentId = 353, NameEn = "Djerba Midoun", NameAr = "جربة ميدون", ParentNameAr = "Medenine", ParentNameEn = "مدنين" });
            states.Add(new state() { Id = 626, ParentId = 353, NameEn = "Medenine", NameAr = "مدنين", ParentNameAr = "Medenine", ParentNameEn = "مدنين" });
            states.Add(new state() { Id = 496, ParentId = 353, NameEn = "Sidi Makhlouf", NameAr = "سيدي مخلوف", ParentNameAr = "Medenine", ParentNameEn = "مدنين" });
            states.Add(new state() { Id = 490, ParentId = 353, NameEn = "Zarzis", NameAr = "جرجيس", ParentNameAr = "Medenine", ParentNameEn = "مدنين" });
            states.Add(new state() { Id = 552, ParentId = 360, NameEn = "Borj El Amri", NameAr = "برج العامري", ParentNameAr = "Manouba", ParentNameEn = "منوبة" });
            states.Add(new state() { Id = 554, ParentId = 360, NameEn = "Douar Hicher", NameAr = "دوار هيشر", ParentNameAr = "Manouba", ParentNameEn = "منوبة" });
            states.Add(new state() { Id = 551, ParentId = 360, NameEn = "El Battan", NameAr = "البطان", ParentNameAr = "Manouba", ParentNameEn = "منوبة" });
            states.Add(new state() { Id = 550, ParentId = 360, NameEn = "Jedaida", NameAr = "الجديدة", ParentNameAr = "Manouba", ParentNameEn = "منوبة" });
            states.Add(new state() { Id = 633, ParentId = 360, NameEn = "Manouba", NameAr = "منوبة", ParentNameAr = "Manouba", ParentNameEn = "منوبة" });
            states.Add(new state() { Id = 555, ParentId = 360, NameEn = "Mornaguia", NameAr = "المرناقية", ParentNameAr = "Manouba", ParentNameEn = "منوبة" });
            states.Add(new state() { Id = 553, ParentId = 360, NameEn = "Oued Ellil", NameAr = "واد الليل", ParentNameAr = "Manouba", ParentNameEn = "منوبة" });
            states.Add(new state() { Id = 556, ParentId = 360, NameEn = "Tebourba", NameAr = "طبربة", ParentNameAr = "Manouba", ParentNameEn = "منوبة" });
            states.Add(new state() { Id = 467, ParentId = 350, NameEn = "Beni Khalled", NameAr = "بني خلاد", ParentNameAr = "Nabeul", ParentNameEn = "نابل" });
            states.Add(new state() { Id = 460, ParentId = 350, NameEn = "Beni Khiar", NameAr = "بني خيار ", ParentNameAr = "Nabeul", ParentNameEn = "نابل" });
            states.Add(new state() { Id = 463, ParentId = 350, NameEn = "Bou Argoub", NameAr = "بوعرقوب", ParentNameAr = "Nabeul", ParentNameEn = "نابل" });
            states.Add(new state() { Id = 468, ParentId = 350, NameEn = "Dar Chaabane Elfehri", NameAr = "دار شعبان الفهري", ParentNameAr = "Nabeul", ParentNameEn = "نابل" });
            states.Add(new state() { Id = 466, ParentId = 350, NameEn = "El Haouaria", NameAr = "الهوارية", ParentNameAr = "Nabeul", ParentNameEn = "نابل" });
            states.Add(new state() { Id = 457, ParentId = 350, NameEn = "El Mida", NameAr = "الميدة", ParentNameAr = "Nabeul", ParentNameEn = "نابل" });
            states.Add(new state() { Id = 464, ParentId = 350, NameEn = "Grombalia", NameAr = "قرمبالية", ParentNameAr = "Nabeul", ParentNameEn = "نابل" });
            states.Add(new state() { Id = 469, ParentId = 350, NameEn = "Hammam Ghezaz", NameAr = "حمام الغزاز", ParentNameAr = "Nabeul", ParentNameEn = "نابل" });
            states.Add(new state() { Id = 461, ParentId = 350, NameEn = "Hammamet", NameAr = "الحمامات", ParentNameAr = "Nabeul", ParentNameEn = "نابل" });
            states.Add(new state() { Id = 455, ParentId = 350, NameEn = "Kelibia", NameAr = "قليبية", ParentNameAr = "Nabeul", ParentNameEn = "نابل" });
            states.Add(new state() { Id = 459, ParentId = 350, NameEn = "Korba", NameAr = "قربة", ParentNameAr = "Nabeul", ParentNameEn = "نابل" });
            states.Add(new state() { Id = 458, ParentId = 350, NameEn = "Menzel Bouzelfa", NameAr = "منزل بوزلفة", ParentNameAr = "Nabeul", ParentNameEn = "نابل" });
            states.Add(new state() { Id = 456, ParentId = 350, NameEn = "Menzel Temime", NameAr = "منزل تميم", ParentNameAr = "Nabeul", ParentNameEn = "نابل" });
            states.Add(new state() { Id = 623, ParentId = 350, NameEn = "Nabeul", NameAr = "نابل", ParentNameAr = "Nabeul", ParentNameEn = "نابل" });
            states.Add(new state() { Id = 465, ParentId = 350, NameEn = "Slimane", NameAr = "سليمان", ParentNameAr = "Nabeul", ParentNameEn = "نابل" });
            states.Add(new state() { Id = 462, ParentId = 350, NameEn = "Takelsa", NameAr = "تاكلسة", ParentNameAr = "Nabeul", ParentNameEn = "نابل" });

        }
    }

    public class state
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public string ParentNameEn { get; set; }
        public string ParentNameAr { get; set; }
    }
}
